name: Deploy to Github Pages
on: 
  push:
    branches: 
      - master

env:
  WORKDIR_CLIENT: src/test-frontend
  WORKDIR_DEST: dest

jobs: 
  deploy:
    name: Deploy to Github Pages
    runs-on: [ubuntu-18.04]
    steps: 
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Angular
        run: npm ci
        working-directory: ${{env.WORKDIR_CLIENT}}

      - name: Build Angular Client
        run: npm run build -- --prod
        working-directory: ${{env.WORKDIR_CLIENT}}

      - name: Copy dist Files
        run: cp -r ${{env.WORKDIR_CLIENT}}/dist ${{env.WORKDIR_DEST}}
        
      - name: Publish to Github Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          # Git branch where assets will be deployed
          target_branch: master
          build_dir: ${{env.WORKDIR_DEST}}
    

